### PR TITLE
Start chapter 6

### PR DESCRIPTION
**Pull request by geraintpalmer**
Known issues:
    + Was not able to run lintr
    + Need to change R plotting to ggplot2
    + Line number of image captions (change once everything complete)

### CODE REVIEW

**Comment by geraintpalmer** [comment]
@drvinceknight The only failure are now variable names containing capital letters (including `deSolve`). Are you happy to merge?

**Comment by drvinceknight** [comment]
> @drvinceknight The only failure are now variable names containing capital letters (including `deSolve`). Are you happy to merge?

Yup excited there are merge conflicts with the base branch. Let me know if I can assist with that or if you'd like me to just go ahead and fix (and push to you etc...).

**Comment by geraintpalmer** [comment]
> Yup excited there are merge conflicts with the base branch. Let me know if I can assist with that or if you'd like me to just go ahead and fix (and push to you etc...).

Merge conflicts are going to be just environment and spellchecker. I'll fix, but I'll wait for you to reconfigure the CI first so master always passes.

**Comment by drvinceknight** [comment]
:+1:

**Comment by drvinceknight** [comment]
You should be able to merge https://github.com/drvinceknight/amwoss/pull/38 (once that last run is completed) and then fix the merge conflict and all should be good :+1:

**Pull request merged**
